account_id = "b3dad22670b88424da9afddc967218a2"
name = "demo-lbrands-frontend"
type = "webpack"
workers_dev = true
kv-namespaces = [
    { binding = "BOOK_IMAGES", id = "1fcd1c0a7aae4c958bde0606dd090d95" }
]
site = { bucket = "./build" }
entry-point = "workers-site"