name = "demo-lbrands-backend"
type = "webpack"

account_id = "b3dad22670b88424da9afddc967218a2"
workers_dev = false
vars = { DC_LIST="play-us-west", C8_URL="https://play.macrometa.io", C8_API_KEY="xxxx" }
kv-namespaces = [
    { binding = "LBRANDS_IMAGES", id = "723596d64b1b43dc876a0c0abbf82e38", preview_id = "723596d64b1b43dc876a0c0abbf82e38" }
]

# The ID of the domain to deploying to
zone_id = "44ccec372ad2478131dc3fd7bf51a6c2"
# The route pattern your Workers application will be served at
route = "cf.macrometa.io/api/*"